from django.contrib import admin
from django.urls import path,include
from SkinCraft_Main import views
from django.conf import settings
from django.conf.urls.static import static
 
urlpatterns = [
    path(getattr(settings, 'ADMIN_DASHBOARD_PATH', 'secret-admin') + '/', views.custom_admin_entry, name='custom_admin_entry'),
    path('admin_dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('returns/<int:return_id>/approve/', views.approve_return, name='approve_return'),
    path('returns/<int:return_id>/reject/', views.reject_return, name='reject_return'),
    path('returns/<int:return_id>/', views.return_details, name='return_details'),
    path('returns/<int:return_id>/refund/', views.process_return_refund, name='process_return_refund'),
    path('api/order/<int:order_id>/details/', views.get_order, name='get_order'),
    path('api/delivery-partner/<int:partner_id>/reviews/', views.get_delivery_partner_reviews, name='get_delivery_partner_reviews'),
    path('api/delivery-partner/create/', views.create_delivery_partner, name='create_delivery_partner'),
    path('inventory/products/create/', views.create_inventory_product, name='create_inventory_product_alt'),
    path('inventory/products/<int:product_id>/update/', views.update_inventory_product, name='update_inventory_product_alt'),
    path('inventory/products/<int:product_id>/delete/', views.delete_inventory_product, name='delete_inventory_product_alt'),
    path('', views.homepage, name='homepage'),
    path('api/order/<int:order_id>/update/', views.update_order, name='update_order'),
    path('api/delivery-partner/<int:partner_id>/toggle/', views.toggle_delivery_partner, name='toggle_delivery_partner'),
    path('api/user/<int:user_id>/toggle/', views.toggle_user_active, name='toggle_user_active'),
    path('api/user/<int:user_id>/delete/', views.delete_user_account, name='delete_user_account'),
    path('api/delivery-partner/<int:partner_id>/delete/', views.delete_delivery_partner, name='delete_delivery_partner'),
    path('salary/process/', views.process_salary_payment, name='process_salary_payment'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('profile/', views.profile_view, name='profile'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('ayurveda/', views.ayurveda_view, name='ayurveda'),
    path('contact/', views.contact, name='contact'),
    path('faq/', views.faq_view, name='faq'),
    path('about/', views.about_view, name='about'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('shipping-policy/', views.shipping_policy, name='shipping_policy'),
    path('terms-and-conditions/', views.terms_conditions, name='terms_conditions'),
    path('delivery/dashboard/', views.delivery_dashboard, name='delivery_dashboard'),
    path('delivery/order/<int:order_id>/status/', views.update_delivery_status, name='update_delivery_status'),
    path('delivery/order/<int:order_id>/send-otp/', views.send_delivery_otp, name='send_delivery_otp'),
    path('delivery/order/<int:order_id>/complete/', views.complete_delivery, name='complete_delivery'),
    path('delivery/helpdesk/submit/', views.submit_helpdesk_ticket, name='submit_helpdesk_ticket'),
    path('delivery/profile/update/', views.update_delivery_profile, name='update_delivery_profile'),
    path('delivery/bank-details/update/', views.update_delivery_bank_details, name='update_delivery_bank_details'),
    path('products/', views.product_list, name='product'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/update/<int:item_id>/<str:action>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('cart/delete/<int:item_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('wishlist/', views.wishlist_view, name='wishlist_view'),
    path('wishlist/toggle/<int:product_id>/', views.toggle_wishlist, name='toggle_wishlist'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('checkout/add-address/', views.add_address_from_checkout, name='add_address_from_checkout'),
    path('razorpay/create-order/', views.create_razorpay_order, name='create_razorpay_order'),
    path('process-order/', views.process_order, name='process_order'),
    path('order-success/<str:order_number>/', views.order_success, name='order_success'),
    path('payment-failed/<str:order_number>/', views.payment_failed, name='payment_failed'),
    path('razorpay/webhook/', views.razorpay_webhook, name='razorpay_webhook'),
    path('knowledge-hub/', views.knowledge_hub, name='knowledge_hub'),
    path('get-order-items/<int:order_id>/', views.get_order_items, name='get_order_items'),
    path('submit-review/', views.submit_review, name='submit_review'),
    path('submit-delivery-review/', views.submit_delivery_partner_review, name='submit_delivery_partner_review'),
    path('submit-return/', views.submit_return, name='submit_return'),
    path('apply-coupon/', views.apply_coupon, name='apply_coupon'),
    path('track-order/', views.track_order, name='track_order'),
    path('confirm-return-pickup/<int:return_id>/', views.confirm_return_pickup, name='confirm_return_pickup'),
    path('invoice/<int:order_id>/', views.invoice_view, name='invoice_view'),
    path('product/<int:product_id>/review/', views.submit_product_review, name='submit_product_review'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
