# Generated by Django 6.0 on 2026-01-30 10:31

import SkinCraft_Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0002_category_contactmessage_producttag_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=SkinCraft_Main.models.product_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=SkinCraft_Main.models.product_gallery_path),
        ),
    ]
