# Generated by Django 6.0 on 2026-02-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='added_at',
        ),
    ]
