# Generated by Django 6.0 on 2026-02-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0006_remove_cart_updated_at_remove_cartitem_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
