# Generated by Django 6.0 on 2026-02-02 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
