# Generated by Django 6.0 on 2026-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0013_order_add_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
