# Generated by Django 6.0 on 2026-02-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0018_order_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='assigned_to',
        ),
    ]
