# Generated by Django 6.0 on 2026-02-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0023_deliveryprofile_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
