# Generated by Django 6.0 on 2026-02-04 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0024_deliveryprofile_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly Salary for the delivery personnel', max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryHelpDeskTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Customer Not Available', 'Customer Not Available'), ('Wrong Address', 'Wrong Address'), ('Payment Issue', 'Payment Issue'), ('Package Damaged', 'Package Damaged'), ('Vehicle Issue', 'Vehicle Issue'), ('Other', 'Other')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpdesk_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
