# Generated by Django 6.0 on 2026-02-05 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0025_alter_deliveryprofile_salary_deliveryhelpdeskticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Damaged', 'Damaged Product'), ('Wrong Item', 'Wrong Item Received'), ('Not as Described', 'Not as Described'), ('Quality Issue', 'Quality Issue'), ('Expired', 'Product Expired'), ('Missing Items', 'Missing Items'), ('Changed Mind', 'Changed Mind'), ('Other', 'Other')], max_length=50)),
                ('issue', models.CharField(max_length=255)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Initiated', 'Initiated'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='SkinCraft_Main.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
