# Generated by Django 6.0 on 2026-02-05 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0026_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Delivery partner assigned for return pickup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_returns', to=settings.AUTH_USER_MODEL),
        ),
    ]
