# Generated by Django 6.0 on 2026-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0027_return_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, help_text='When the return item was picked up', null=True),
        ),
    ]
