# Generated by Django 6.0.1 on 2026-02-06 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0032_deliverypartnerreview_salarypayment'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='SalaryPayment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('month', models.IntegerField(help_text='Month (1-12)')),
                        ('year', models.IntegerField(help_text='Year (e.g., 2026)')),
                        ('base_salary', models.DecimalField(decimal_places=2, help_text='Base monthly salary', max_digits=10)),
                        ('bonus', models.DecimalField(decimal_places=2, default=0, help_text='Performance bonus', max_digits=10)),
                        ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Deductions (if any)', max_digits=10)),
                        ('net_salary', models.DecimalField(decimal_places=2, help_text='Final amount to be paid', max_digits=10)),
                        ('deliveries_completed', models.IntegerField(default=0, help_text='Total deliveries completed in the month')),
                        ('returns_completed', models.IntegerField(default=0, help_text='Total returns picked up in the month')),
                        ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                        ('payment_mode', models.CharField(blank=True, choices=[('Bank Transfer', 'Bank Transfer'), ('Cash', 'Cash'), ('UPI', 'UPI'), ('Cheque', 'Cheque')], max_length=20, null=True)),
                        ('transaction_reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                        ('remarks', models.TextField(blank=True, help_text='Additional notes or remarks', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('paid_at', models.DateTimeField(blank=True, null=True)),
                        ('delivery_partner', models.ForeignKey(limit_choices_to={'role': 'Delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                        ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salaries_processed', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Salary Payment',
                        'verbose_name_plural': 'Salary Payments',
                        'ordering': ['-year', '-month', '-created_at'],
                        'unique_together': {('delivery_partner', 'month', 'year')},
                    },
                ),
            ],
        ),
    ]