# Generated by Django 6.0 on 2026-02-06 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0035_coupon_order_coupon_code_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryhelpdeskticket',
            name='admin_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryhelpdeskticket',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryhelpdeskticket',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_replies', to=settings.AUTH_USER_MODEL),
        ),
    ]
