# Generated by Django 6.0 on 2026-02-08 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0036_deliveryhelpdeskticket_admin_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='return_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_record', to='SkinCraft_Main.return'),
        ),
    ]
