# Generated by Django 6.0 on 2026-02-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0037_alter_refund_return_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
