# Generated by Django 6.0 on 2026-02-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0038_refund_refund_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='return_request',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='upi_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
