# Generated by Django 6.0 on 2026-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkinCraft_Main', '0041_alter_salarypayment_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='transfer_account_holder_name',
            field=models.CharField(blank=True, help_text='Snapshot of account holder used for this transfer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='transfer_account_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of account number used for this transfer', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='transfer_bank_name',
            field=models.CharField(blank=True, help_text='Snapshot of bank name used for this transfer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='transfer_ifsc_code',
            field=models.CharField(blank=True, help_text='Snapshot of IFSC used for this transfer', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='transfer_upi_id',
            field=models.CharField(blank=True, help_text='Snapshot of UPI ID used for this transfer', max_length=100, null=True),
        ),
    ]
